name: bestbooks-server
base: core22 
version: '1.1.0'
summary: Standalone API server for BestBooks Accounting Application Framework
description: |
  Standalone API server for BestBooks Accounting Application Framework

grade: stable
confinement: strict
architectures: [amd64, arm64, armhf, i386]

parts:
  my-part:
    # See 'snapcraft plugins'
    plugin: nil
